"""add models

Revision ID: 61514d7c3872
Revises: 
Create Date: 2024-11-30 14:13:07.151025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61514d7c3872'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_accounts_discord_id'), 'discord_accounts', ['discord_id'], unique=True)
    op.create_table('wikidot_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikidot_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('unixname', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wikidot_accounts_wikidot_id'), 'wikidot_accounts', ['wikidot_id'], unique=True)
    op.create_table('link_request_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('discord_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discord_account_id'], ['discord_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_link_request_tokens_discord_account_id'), 'link_request_tokens', ['discord_account_id'], unique=False)
    op.create_table('linked_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('wikidot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discord_id'], ['discord_accounts.discord_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wikidot_id'], ['wikidot_accounts.wikidot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_accounts_discord_id'), 'linked_accounts', ['discord_id'], unique=False)
    op.create_index(op.f('ix_linked_accounts_wikidot_id'), 'linked_accounts', ['wikidot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linked_accounts_wikidot_id'), table_name='linked_accounts')
    op.drop_index(op.f('ix_linked_accounts_discord_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    op.drop_index(op.f('ix_link_request_tokens_discord_account_id'), table_name='link_request_tokens')
    op.drop_table('link_request_tokens')
    op.drop_index(op.f('ix_wikidot_accounts_wikidot_id'), table_name='wikidot_accounts')
    op.drop_table('wikidot_accounts')
    op.drop_index(op.f('ix_discord_accounts_discord_id'), table_name='discord_accounts')
    op.drop_table('discord_accounts')
    # ### end Alembic commands ###
