"""add is_jp_member column

Revision ID: 33b855147da5
Revises: 61514d7c3872
Create Date: 2024-12-02 10:39:19.004333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33b855147da5"
down_revision: Union[str, None] = "61514d7c3872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikidot_accounts",
        sa.Column(
            "is_jp_member",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikidot_accounts", "is_jp_member")
    # ### end Alembic commands ###
