"""add unlink column

Revision ID: 931e45c18b3a
Revises: 33b855147da5
Create Date: 2024-12-02 18:14:28.736388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931e45c18b3a'
down_revision: Union[str, None] = '33b855147da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linked_accounts', 'unlinked_at')
    # ### end Alembic commands ###
